Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,3 +47,19 @@ jobs:
                 }
                 }
                updateComment(github);
+      - name: Notify Team on Failure
+        run: |
+
+                echo "##############################################" 
+                cat quality_status.txt
+                echo "##############################################" 
+                
+                if grep -q "failure" quality_status.txt; then
+                  
+                  echo "Send Notification to MS Teams";
+                
+                  echo "{\"@type\":\"MessageCard\",\"@context\":\"https://schema.org/extensions\",\"summary\":\" Quality check failed!\",\"themeColor\":\"ff0000\",\"title\":\"💢 Code Quality check failed ! 💢\",\"sections\":[{\"facts\":[{\"name\":\"Repository:\",\"value\":\"$GITHUB_REPOSITORY\"},{\"name\":\"Branch:\",\"value\":\"$GITHUB_REF_NAME\"},{\"name\":\"Git User:\",\"value\":\"$GITHUB_ACTOR\"},{\"name\":\"Commit:\",\"value\":\"$GITHUB_SHA\"}]}],\"potentialAction\":[{\"@type\":\"OpenUri\",\"name\":\"View on GitHub\",\"targets\":[{\"os\":\"default\",\"uri\":\"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}]}]}" > failed.json
+                  curl -X POST -H 'Content-Type: application/json' -s -d @failed.json ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
+
+                  exit 1
+                fi
